### ISSUE TITLE
Feedback global.py

### ISSUE THREAD

**Issue by wpreimes** [lrachbau/qa4sm-reader#2]
- L5-7 https://github.com/lrachbau/qa4sm-reader/blob/ffb453d0299d98961ef28674eae23e8d0cf6eab1/src/qa4sm_reader/globals.py#L5 Add the lincence statement of our group instead (eg take it form [here](https://github.com/TUW-GEO/ascat/blob/master/ascat/h_saf.py)
- https://github.com/lrachbau/qa4sm-reader/blob/ffb453d0299d98961ef28674eae23e8d0cf6eab1/src/qa4sm_reader/globals.py#L58 No need to keep the wrong 'ERA' dataset (that was never in production I think) --> also for the other dicts.
- https://github.com/lrachbau/qa4sm-reader/blob/ffb453d0299d98961ef28674eae23e8d0cf6eab1/src/qa4sm_reader/globals.py#L115 : full name is SMAP L3 Radiometer Global Daily 36 km EASE-Grid Soil Moisture, maybe try to add a few for infos into the long name (not all, because I guess it would be too long).

**Comment by wpreimes** [comment]
I think it's a good idea to collect all the default settings in global.py. Also the list of datasets which require scatter plots is good, maybe you can explain the settings a bit more and move the non-dicts to the top.  https://github.com/lrachbau/qa4sm-reader/blob/ffb453d0299d98961ef28674eae23e8d0cf6eab1/src/qa4sm_reader/globals.py#L148

**Comment by lrachbau** [comment]
> full name is SMAP L3
I took those names from qa4sm\validator\fixtures\datasets.json - i think they should be changed there first.
Anyways, tracy is going to add the pretty names to the metadata, then it will use those instead of falling back to the strings in the globals.py.
